### ISSUE TITLE
Failure to install on Ubuntu

### ISSUE THREAD

**Issue by jmeeter** [sayanarijit/qrscan#12]
Tried installing on fresh copy of Ubuntu 22.04 and 20.04 and am receiving this error both times:

>  Compiling nasm-rs v0.2.4
> error: failed to run custom build command for `v4l2-sys-mit v0.2.0`
> 
> Caused by:
>   process didn't exit successfully: `/tmp/cargo-installNHPPng/release/build/v4l2-sys-mit-3b1612bc27ecc5ea/build-script-build` (exit status: 101)
>   --- stderr
>   thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.56.0/src/lib.rs:1922:31
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> error: failed to compile `qrscan v0.1.7`, intermediate artifacts can be found at `/tmp/cargo-installNHPPng`

**Comment by sayanarijit** [comment]
Thanks for reporting. I haven't been able to compile it since I moved to NixOS, so I thought it's a NixOS specific issue.

For now, you can download and use the [pre-built binaries](https://github.com/sayanarijit/qrscan/releases/tag/v0.1.7). Later I'll try to debug it on a different OS.

**Comment by jmeeter** [comment]
No problem, it was easily fixed by running `sudo apt-get install libclang-dev` then rerunning cargo. :)

**Comment by sayanarijit** [comment]
Glad it worked. I have updated the readme.

So, it is a NixOS specific issue... Struggle continues.
